# auto generate by helm repo add bitnami https://charts.bitnami.com/bitnami
# helm install rabbit --set service.type=NodePort bitnami/rabbitmq --namespace ecommerce
# kubectl get secret rabbit-rabbitmq -o yaml -n ecommerce

apiVersion: v1
data:
  rabbitmq-erlang-cookie: b0NGVXliM3hWd3Y3MEZRU2JRSWhvaE9DVjV5SjdrRWk=
  rabbitmq-password: ZnFZS2pCTjB4c0xqMGt3RQ==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: rabbit
    meta.helm.sh/release-namespace: ecommerce
  creationTimestamp: '2024-03-13T19:42:45Z'
  labels:
    app.kubernetes.io/instance: rabbit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/version: 3.12.13
    helm.sh/chart: rabbitmq-12.15.0
  name: rabbit-rabbitmq
  namespace: ecommerce
  resourceVersion: '776'
  uid: 0b6f0c91-3ffe-403d-ad45-a34385ad88c4
type: Opaque
