apiVersion: apps/v1 # Versi API Kubernetes yang digunakan
kind: Deployment # Jenis objek Kubernetes yang akan dibuat (Deployment)
metadata:
  name: shipping # Nama untuk Deployment yang akan dibuat
  labels:
    app: shipping # Label yang diterapkan pada Deployment untuk identifikasi
spec:
  replicas: 1 # Jumlah replika yang akan dibuat
  selector:
    matchLabels:
      app: shipping # Selektor yang digunakan untuk memilih pod yang akan dimasukkan ke dalam Deployment
  template:
    metadata:
      labels:
        app: shipping # Label yang diterapkan pada pod yang akan dibuat oleh Deployment
    spec:
      containers:
        - name: shipping # Nama dari container dalam pod
          image: ghcr.io/lyrihkaesa/shipping:latest # Image Docker yang akan digunakan
          ports:
            - containerPort: 3001 # Port yang di-expose oleh container dalam pod
          env:
            # Port yang di-expose shipping app
            - name: PORT
              value: '3001'
            # URL RabbitMQ user:<password dari perintah echo $(kubectl get secret --namespace ecommerce rabbit-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 -d)>@nama-service-rabbit-mq:port yang diekspose oleh service rabbitmq
            - name: AMQP_URL
              value: amqp://user:fqYKjBN0xsLj0kwE@rabbit-rabbitmq:5672
